[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling" ]

[project]
name = "spatiato"
version = "0.2.1"
description = "A spatial omics interface for napari."
readme = "README.md"
requires-python = ">=3.12,<3.15"
license = { file = "LICENSE" }
authors = [
    { name = "VIB spatial catalyst" }
]

keywords = [
    "napari",
    "plugin",
    "object-classification",
    "image-analysis",
    "spatialdata",
    "anndata",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: napari",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Image Processing",
]

dependencies = [
    "dask[dataframe]",
    "filelock>=3.20.1",
    "harpy-analysis>=0.4.4",
    "spatialdata>=0.7.2",
    "joblib",
    "lazy-loader>=0.4",
    "loguru",
    "napari[all]>=0.4.18",
    "pandas<3.0",
    "pyarrow",
    "pyqtgraph>=0.13.7",
]

# TODO: change to dependency-groups once pip has support https://github.com/pypa/pip/issues/12963
[project.optional-dependencies]
torch = [
    "torchvision",
]
test = [
    "pytest",
    "pytest-cov",
    "pytest-qt",
    "pytest-xdist",
    "tox",
]
docs = [
    "sphinx>=4.5",
    "sphinx-book-theme>=1.0.0",
    "sphinx_rtd_theme",
    "myst-nb",
    "sphinxcontrib-bibtex>=1.0.0",
    "sphinx-autodoc-typehints",
    "sphinx-design",
    "sphinx-copybutton",
]
dev = [
    "pre-commit",
    "ruff",
    "twine>=4.0.2",
    "spatiato[test,docs,torch]",
]

[project.entry-points."napari.manifest"]
spatiato = "spatiato:napari.yaml"

[project.urls]
Homepage = "https://github.com/vibspatial/spatiato"
Documentation = "https://github.com/vibspatial/spatiato#readme"
Repository = "https://github.com/vibspatial/spatiato"
Issues = "https://github.com/vibspatial/spatiato/issues"
Changelog = "https://github.com/vibspatial/spatiato/releases"
Paper = "https://doi.org/10.1093/bioinformatics/btag122"
SaeysLab = "https://saeyslab.sites.vib.be/en"
VIBSpatialCatalyst = "https://vib.be/en/technologies/technology-portfolio/spatial-catalyst"


[tool.coverage.run]
source = ["spatiato"]
omit = ["tests/*", "docs/*"]

[tool.ruff]
src = ["src"]
line-length = 120
select = [
    "F",  # Errors detected by Pyflakes
    "E",  # Error detected by Pycodestyle
    "W",  # Warning detected by Pycodestyle
    "I",  # isort
    "D",  # pydocstyle
    "B",  # flake8-bugbear
    "TID",  # flake8-tidy-imports
    "C4",  # flake8-comprehensions
    "BLE",  # flake8-blind-except
    "UP",  # pyupgrade
    "RUF100",  # Report unused noqa directives
]
ignore = [
    # line too long -> we accept long comment lines; formatter gets rid of long code lines
    "E501",
    # Do not assign a lambda expression, use a def -> lambda expression assignments are convenient
    "E731",
    # allow I, O, l as variable names -> I is the identity matrix
    "E741",
    # Missing docstring in public package
    "D104",
    # Missing docstring in public module
    "D100",
    # Missing docstring in __init__
    "D107",
    # Errors from function calls in argument defaults. These are fine when the result is immutable.
    "B008",
    # __magic__ methods are are often self-explanatory, allow missing docstrings
    "D105",
    # first line should end with a period [Bug: doesn't work with single-line docstrings]
    "D400",
    # First line should be in imperative mood; try rephrasing
    "D401",
    ## Disable one in each pair of mutually incompatible rules
    # We don’t want a blank line before a class docstring
    "D203",
    # We want docstrings to start immediately after the opening triple quote
    "D213",
]
extend-include = ["*.ipynb"]

[tool.hatch.build.targets.wheel]
packages = ["src/spatiato"]

[tool.hatch.build.targets.wheel.force-include]
"src/spatiato/napari.yaml" = "spatiato/napari.yaml"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.envs.default]
installer = "uv"
features = [ "dev" ]

[tool.hatch.envs.docs]
features = [ "dev" ]
scripts.build = "sphinx-build -M html docs docs/_build {args}"
scripts.open = "python -m webbrowser -t docs/_build/html/index.html"
scripts.clean = "git clean -fdX -- {args:docs}"

[tool.hatch.envs.hatch-test]
features = [ "dev" ]

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.ruff.per-file-ignores]
"docs/*" = ["I"]
"src/spatiato/core/*.py" = ["D"]
"src/spatiato/viewer/*.py" = ["D"]
"src/spatiato/widgets/*.py" = ["D"]
"src/spatiato/widgets/**/*.py" = ["D"]
"tests/*" = ["D"]
"**/_tests/*" = ["D"]
"*/__init__.py" = ["F401"]
"**/test_data/*" = ["ALL"]

[tool.pytest.ini_options]
testpaths = ['tests']
xfail_strict = true
addopts = [
  "--import-mode=importlib", # allow using test files with same name
]
